const Projects = {
    "development": {
        "constellationCove": {
            name: "Constellation Cove",
            description: "",
            contributions: [],
            type: "Senior Capstone",
            githubLink: "",
            projectLink: "",
            date: "",
            tools: [],
        },
        "wichack24": {
            name: "",
            description: "",
            contributions: [],
            type: " ",
            githubLink: "",
            projectLink: "",
            date: "",
            tools: [],
        },
        "waterScale": {
            name: "",
            description: "",
            contributions: [],
            type: " ",
            githubLink: "",
            projectLink: "",
            date: "",
            tools: [],
        },
        "spellingBeeBestie": {
            name: "Spelling Bee Bestie",
            description: "",
            contributions: [],
            type: "",
            githubLink: "https://github.com/nihalkarim/spelling-bee-bestie",
            projectLink: "https://nk1327-spelling-bee-6c53c0b39b6d.herokuapp.com/letter",
            date: "",
            tools: [],
        },
        "multiTasker": {
            name: "",
            description: "",
            contributions: [],
            type: "",
            githubLink: "",
            projectLink: "https://www.youtube.com/watch?v=g0C0gj80fQI",
            date: "",
            tools: [],
        },
        "dummy": {
            name: "",
            description: "",
            contributions: [],
            type: "",
            githubLink: "",
            projectLink: "https://editor.p5js.org/nk1327/sketches/CKfYEDgsQ",
            date: "",
            tools: [],
        },
        "recipeApp": {
            name: "",
            description: "",
            contributions: [],
            type: "",
            githubLink: "https://github.com/nihalkarim/nk1327-igme430-project1",
            projectLink: "https://nk1327-project1-d895b0459c56.herokuapp.com",
            date: "",
            tools: [],
        },
        "chromeExtension": {
            name: "",
            description: "",
            contributions: [],
            type: "",
            githubLink: "https://github.com/nihalkarim/480-5a",
            projectLink: "",
            date: "",
            tools: [],
        },
        "inventori": {
            name: "Inventori",
            description: "",
            contributions: [],
            type: "",
            githubLink: "https://github.com/AdventureSlugg/inventori",
            projectLink: "",
            date: "February 2023",
            tools: ['Arduino', 'Node.js', 'Angular', 'C++', 'Bootstrap', 'CSS', 'CSV'],
        },
        "hotFoods": {
            name: "Hot Foods",
            description: "",
            contributions: [],
            type: "Hackathon",
            githubLink: "https://github.com/RubbaBoy/hot_foods",
            projectLink: "https://www.figma.com/proto/x4Rh2tbhS7uqSdpmUyGvN4/Hot-Foods?node-id=64-1870&scaling=scale-down&page-id=0%3A1",
            date: "February 2023",
            tools: ['Dart', 'Docker', 'Flutter', 'postgreSQL', 'Java Spring Boot', 'Figma', 'Adobe Photoshop', 'Adobe Illustrator', 'NetNutrition'],
        },
        "meshGradientGenerator": {
            name: "Mesh Gradient Generator",
            description: "",
            contributions: [],
            type: "Class Project",
            githubLink: "",
            projectLink: "https://people.rit.edu/nk1327/235/karim-p3/index.html",
            date: "December 2022",
            tools: ['Javascript', 'HTML', 'CSS', 'DOM Manipulation'],
        },
        "dataMapVis": {
            name: "CDC Data Map Visualization",
            description: "",
            contributions: [],
            type: "Class Project",
            githubLink: "https://github.com/nihalkarim/spring22-projects/tree/main/P2_Karim%20",
            projectLink: "",
            date: "April 2022",
            tools: ['P5 JS', `HTML`, `JSON`, 'Adobe Illustrator'],
        },
        "catArray": {
            name: "Cat Array",
            description: "",
            contributions: [],
            type: "Class Project",
            githubLink: "https://github.com/nihalkarim/spring22-P1",
            projectLink: "",
            date: "September 2021",
            tools: ['P5 JS', `HTML`, `JSON`],
        },
    },
    "design": {
        "witr": {
            name: "WITR 89.7 Website Redesign",
            description: "",
            contributions: ['UI/UX Design', 'Wireframing', 'Prototyping', 'User Research'],
            type: "Work",
            githubLink: "",
            projectLink: "https://witr.rit.edu",
            date: "February 2022 - May 2022",
            tools: ["Adobe Photoshop", "Adobe Illustrator", "Figma"],
        },
        "coffeeCorner": {
            name: "",
            description: "",
            contributions: [],
            type: "Hackathon",
            githubLink: "",
            projectLink: "https://www.figma.com/proto/PDYjc10xr1aMISE3UtNK62/Roc-Coffee-Corner?node-id=2-18&starting-point-node-id=2%3A18&scaling=scale-down",
            date: "February 2022",
            tools: ["Adobe Photoshop", "Adobe Illustrator", "Figma"],
        },
        "adhdPoster": {
            name: "ADHD Awareness Poster Ad",
            description: "",
            contributions: [],
            type: "Class Project",
            githubLink: "",
            projectLink: "",
            date: "December 2021",
            tools: ["Adobe Photoshop", "Adobe Illustrator", "Figma"],
        },
        "designerExploration": {
            name: "Michael Bierut - Designer Exploration",
            description: "",
            contributions: [],
            type: "Class Project",
            githubLink: "",
            projectLink: "",
            date: "November 2021",
            tools: ["Adobe Photoshop", "Adobe Illustrator", "Figma"],
        },
        "adPoster": {
            name: "Roc City Skatepark Ad Poster",
            description: "",
            contributions: [],
            type: "Class Project",
            githubLink: "",
            projectLink: "",
            date: "October 2021",
            tools: ["Adobe Photoshop", "Adobe Illustrator", "Figma"],
        },
        "dustJacket": {
            name: "Invisible Man Dust Jacket",
            description: "",
            contributions: [],
            type: "Class Project",
            githubLink: "",
            projectLink: "",
            date: "April 2021",
            tools: ["Adobe Photoshop", "Adobe Illustrator"],
        },
    },
}